spring:
  application:
    name: boot-assist
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: woo
      password: ${DEFAULT_USER_PASSWORD:woo00}

server:
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: INFO
    woos.bookassist: DEBUG

openapi:
  kakao:
    appKey: ${DEVKAKAO_APP_KEY}

kakao:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: https://dapi.kakao.com