spring:
  application:
    name: boot-assist
  cache:
    cache-names: top10Queries
    caffeine:
      spec: expireAfterWrite=10s
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: woo
      password: ${DEFAULT_USER_PASSWORD:woo00}

server:
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: INFO
    woos.bookassist: DEBUG
    org.springframework.retry.support.RetryTemplate: DEBUG

feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3000
  threadpool:
    default:
      coreSize: 10
      maximumSize: 100
      allowMaximumSizeToDivergeFromCoreSize: true

ribbon:
  eager-load:
    enabled: true
    clients: kakao, naver
  ConnectTimeout: 200
  ReadTimeout: 2000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 0

openapi:
  kakao:
    appKey: ${DEVKAKAO_APP_KEY}
  naver:
    clientId: ${DEVNAVER_CLIENT_ID}
    clientSecret: ${DEVNAVER_CLIENT_SECRET}

kakao:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: https://dapi.kakao.com

naver:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: https://openapi.naver.com
