spring:
  application:
    name: boot-assist
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: woo
      password: ${DEFAULT_USER_PASSWORD:woo00}

server:
  tomcat:
    uri-encoding: UTF-8

logging:
  level:
    root: INFO
    woos.bookassist: DEBUG

openapi:
  kakao:
    appKey: ${DEVKAKAO_APP_KEY}
  naver:
    clientId: ${DEVNAVER_CLIENT_ID}
    clientSecret: ${DEVNAVER_CLIENT_SECRET}

kakao:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: https://dapi.kakao.com

naver:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: https://openapi.naver.com
